# Generated by Django 5.2.1 on 2025-05-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
    ]
